### ISSUE TITLE
Multiple instances of apps

### ISSUE THREAD

**Issue by pazport** [coder8338/appbox_installer#1]
hello. i have used this app. and it's brill 👍  any way. you could make it so we can install multiple sabnzbd 
1 sabnzbdtv
2 sabnzbdmovies

**Comment by AliceDTRH** [comment]
Is this a different type of software or are you asking to be able to install multiple instances of the software?

**Comment by coder8338** [comment]
Having multiple instances of the same app is probably outside the remit of this installer. If more people want it though, we could consider it.

I'll leave this open for a while in order to gauge interest, just leave a thumbs up if you'd like to see this!

**Comment by pazport** [comment]
> 
> 
> Is this a different type of software or are you asking to be able to install multiple instances of the software?

to be able to install multiple instances of the software. so like i could have like 2 sonarr's and 2 radarr's. and more instances of downloaders e.g SABnzbd and NZBget. sorry i wasn't very clear the 1st time

**Comment by Pagnor** [comment]
Having multi installs of SABnzbd wouldnt be a great idea Sab is very resource intensive so running 2 would cause a maasive drop in useability

**Comment by ghost** [comment]
Sorry to bump this, but is it possible to add a 2nd instance of Sonarr?
E.g. if you need a 2nd Sonarr instance for 4K content. 
Pretty sure that's not possible with a single Sonarr instance, if you need two separate libraries.

**Comment by Pagnor** [comment]
AFAIK this cant be done you would need a second box or a second install of the ubuntu app running

**Comment by ghost** [comment]
It might actually be possible without having a 2nd Sonarr, now that I think about it.. Using quality profiles for the separate 4K library/folders

**Comment by Pagnor** [comment]
I dont think that works as you can only have 1 instance of one film or tv show as far as i am aware

**Comment by ghost** [comment]
Hmm.. Would it be possible if I install another OS on the appbox and run the 2nd Sonarr from there??

**Comment by Pagnor** [comment]
you can install another ubuntu and do it that way

**Comment by AliceDTRH** [comment]
If you have different libraries it should be possible, right?

**Comment by coder8338** [comment]
If anyone wants to implement this you'd need to do something like:

Check first if you can install multiple (some apps can only ever be installed in a single instance)
Ask the user what to call the install, check it's not already in use
Use the install name for the appbox_installer folder, service name and nginx proxy
You would also need to make sure that every app sets a configuration path, and have that created using the install name from above

**Comment by coder8338** [comment]
I'm not maintaining this installer anymore. Switching to a new way of installing apps: https://github.com/coder8338/appbox_swizzin_installer

Please request this feature here: https://feathub.com/liaralabs/swizzin
