### ISSUE TITLE
Look into adding organizr to the script

### ISSUE THREAD

**Issue by AliceDTRH** [coder8338/appbox_installer#10]
https://organizr.app/howtos/

**Comment by AliceDTRH** [comment]
Blocked by #9

**Comment by coder8338** [comment]
@AliceDTRH  Are you working on a PR for this? I can take a look if not.

**Comment by AliceDTRH** [comment]
It first needs #9 to be added but yeah, I was planning on working on that first.
But if you want to do that instead I have no complaints 👍

**Comment by coder8338** [comment]
I have finished adding organizr now.
