### ISSUE TITLE
Issue with Bazarr

### ISSUE THREAD

**Issue by gwenvador** [coder8338/appbox_installer#11]
Bazarr is not working. Looking quickly at the code it seems that the issue is on line 225-226:
`    sed -i 's/name="settings_general_baseurl"/name="settings_general_baseurl" value="{{settings.general.base_url}}"/g' /opt/bazarr/views/wizard_general.tpl
    sed -i '0,/base_url = \//s//base_url = \/bazarr\//' /opt/bazarr/data/config/config.ini`

1. /opt/bazarr/views/wizard_general.tpl does not exist
2. sed is modifying the wrong line. It should be replaced by `sed -i '0,/base_url = /s//base_url = \/bazarr/ /opt/bazarr/data/config/config.ini`

I have tried to modified the config.ini but it is still not working. There might be some changes to be done on the nginx configuration. See [bazarr reverse proxy help](https://github.com/morpheus65535/bazarr/wiki/Reverse-Proxy-Help)

**Comment by coder8338** [comment]
Thanks for the report, this is fixed now.
