### ISSUE TITLE
Latest Radarr Is Not Installing

### ISSUE THREAD

**Issue by AnythingOldSkewl** [coder8338/appbox_installer#15]
Hi. the latest radarr is not installing. The new script doesn't even create the radarr folder. Here is the log, I'm not sure if I understand these errors.

Setting up radarr..
radarr: ERROR (not running)
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/appbox/.wget-hsts'. HSTS will be disabled.
--2021-01-10 10:04:45--  https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
Resolving packages.microsoft.com (packages.microsoft.com)... 13.81.215.193
Connecting to packages.microsoft.com (packages.microsoft.com)|13.81.215.193|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3132 (3.1K) [application/octet-stream]
Saving to: ‘packages-microsoft-prod.deb’

packages-microsoft- 100%[===================>]   3.06K  --.-KB/s    in 0s      

2021-01-10 10:04:45 (300 MB/s) - ‘packages-microsoft-prod.deb’ saved [3132/3132]

(Reading database ... 100814 files and directories currently installed.)
Preparing to unpack packages-microsoft-prod.deb ...
Unpacking packages-microsoft-prod (1.0-ubuntu18.04.2) over (1.0-ubuntu18.04.2) ...
Setting up packages-microsoft-prod (1.0-ubuntu18.04.2) ...
Hit:1 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]      
Get:3 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]    
Hit:4 http://ppa.launchpad.net/embrosyn/xapps/ubuntu bionic InRelease          
Hit:5 http://download.mono-project.com/repo/ubuntu bionic InRelease            
Hit:6 http://ppa.launchpad.net/jcfp/ppa/ubuntu bionic InRelease                
Hit:7 http://dl.winehq.org/wine-builds/ubuntu artful InRelease                 
Get:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]    
Hit:9 http://ppa.launchpad.net/linuxuprising/java/ubuntu bionic InRelease      
Hit:10 http://ppa.launchpad.net/plushuang-tw/uget-stable/ubuntu bionic InRelease
Hit:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease       
Hit:12 http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu bionic InRelease
Ign:13 https://mkvtoolnix.download/ubuntu bionic InRelease                     
Hit:14 http://ppa.launchpad.net/stebbins/handbrake-git-snapshots/ubuntu bionic InRelease
Hit:15 https://mkvtoolnix.download/ubuntu bionic Release                       
Hit:16 http://ppa.launchpad.net/stebbins/handbrake-releases/ubuntu bionic InRelease
Hit:17 https://apt.sonarr.tv/ubuntu bionic InRelease                           
Fetched 252 kB in 2s (108 kB/s)                   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
198 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libmediainfo0v5 is already the newest version (17.12-1ubuntu0.1).
dotnet-runtime-3.1 is already the newest version (3.1.10-1).
The following packages were automatically installed and are no longer required:
  gconf-service gconf-service-backend gconf2 gconf2-common libart-2.0-2
  libavahi-glib1 libbonobo2-0 libbonobo2-common libbonoboui2-0
  libbonoboui2-common libboost-regex1.65.1 libgconf-2-4 libgnome-2-0
  libgnome-keyring-common libgnome-keyring0 libgnome2-common libgnomecanvas2-0
  libgnomecanvas2-common libgnomeui-0 libgnomeui-common libgnomevfs2-0
  libgnomevfs2-common libjpeg-turbo-progs libllvm9 libllvm9:i386 liborbit-2-0
  miscfiles wine-stable wine-stable-amd64 wine-stable-i386:i386
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 198 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up oracle-java11-installer-local (11.0.9-1~linuxuprising0) ...
Before installing this package,
please download the Oracle JDK 11 .tar.gz file
with the same version as this package (version 11.0.4),
and place it in /var/cache/oracle-jdk11-installer-local,

E.g.:
sudo mkdir -p /var/cache/oracle-jdk11-installer-local
sudo cp jdk-11.0.4_linux-x64_bin.tar.gz /var/cache/oracle-jdk11-installer-local/
sha256sum mismatch jdk-11.0.9_linux-x64_bin.tar.gz
Oracle JDK 11 is NOT installed.
dpkg: error processing package oracle-java11-installer-local (--configure):
 installed oracle-java11-installer-local package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 oracle-java11-installer-local
E: Sub-process /usr/bin/dpkg returned an error code (1)
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
tar (child): Radarr.master.*.linux-core-x64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
bash: /opt/Radarr/Radarr: No such file or directory
/dev/fd/63: line 131: kill: (4240) - No such process
radarr: ERROR (spawn error)

**Comment by coder8338** [comment]
Thanks, it's fixed now.
