### ISSUE TITLE
502 error after setting up komga and ombi

### ISSUE THREAD

**Issue by sanskarlather** [coder8338/appbox_installer#16]
After running the script and setting up ombi and komga when I try to open the link it shows a  502 bad gateway and medusa is stuck on loading other services like couch potato and sonarr work seamlessly.
I would also like to know how to shutdown the service it doesn't seem to work when I do it from the gui any help would be appreciated

**Comment by coder8338** [comment]
It sounds like your vnc instance might of run out of ram.

Can you check the monitoring page of the app on the appbox website? You could ask them to add more ram.

To stop a service:

`sudo supervisorctl stop <service name>`

To start a service:

`sudo supervisorctl start <service name>`

To restart a service:

`sudo supervisorctl restart <service name>`

For example, to stop radarr you would run:

`sudo supervisorctl stop radarr`

**Comment by coder8338** [comment]
Also you can check each service log file in `/tmp`

**Comment by sanskarlather** [comment]
Thanks for this quick response, It seems that the ram was the problem I stopped some unused services and tried again and it seems to work I just might have to ask them to increase the ram allocation for my vnc instance
