### ISSUE TITLE
NZBhydra2: Can't Complete Install...

### ISSUE THREAD

**Issue by AnythingOldSkewl** [coder8338/appbox_installer#17]
Hi,

This is the continuous error I get when trying to install.

![hydra](https://user-images.githubusercontent.com/42495993/107113390-aae64700-682c-11eb-8d73-a0e8c3de37ac.jpg)

**Comment by coder8338** [comment]
Fixed by bac7065bdee05f4bd27cb0e734f52650b2f78b07 you need Ubuntu 20.04
