### ISSUE TITLE
Missing Files When Updating Sonarr

### ISSUE THREAD

**Issue by AnythingOldSkewl** [coder8338/appbox_installer#18]
Errors using the script when updating Sonarr @coder8338 

![Sonarr error](https://user-images.githubusercontent.com/42495993/108482884-0ae6df80-7268-11eb-89b2-03b5e45fb938.jpg)

**Comment by AnythingOldSkewl** [comment]
@coder8338 Anybody home?

**Comment by coder8338** [comment]
Please try Ubuntu 20.04
