### ISSUE TITLE
Where is the sonarr located in the file explorer?

### ISSUE THREAD

**Issue by IAmBlackat** [coder8338/appbox_installer#19]
Hi,
Where is the sonarr located in the file explorer?

I am thinking to integrate the re encode (ffmpeg) with it but I am uanble to find the sonarr folder to update some files.

Thanks

**Comment by IAmBlackat** [comment]
I want to edit 

/config/autoProcess.ini
but I didn't found it anywhere

**Comment by coder8338** [comment]
I don't think it's possible to access it outside of the VNC app (via the desktop or SSH) on Ubuntu 18.04. It should be accessible on Ubuntu 20.04.
