### ISSUE TITLE
ubuntu 20.04

### ISSUE THREAD

**Issue by kelvinguy85** [coder8338/appbox_installer#21]
ubuntu 20.04 has been released but your code no longer works on it, it will need to be rewritten

this comes up when trying to use the script 

 Checking if nginx is installed: [ YES ]
/dev/fd/63: line 41: /etc/supervisor/conf.d/nginx.conf: No such file or directory

**Comment by coder8338** [comment]
I just saw it in the app store. I'm working on it now: https://github.com/coder8338/appbox_installer/tree/Ubuntu-20.04
