### ISSUE TITLE
Lidarr issue

### ISSUE THREAD

**Issue by Pagnor** [coder8338/appbox_installer#22]
When installing lidarr this happens

tar (child): Lidarr.develop.*.linux.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now

then a constant scroll of

grep: /home/appbox/.config/Lidarr/config.xml: No such file or directory
grep: /home/appbox/.config/Lidarr/config.xml: No such file or directory
grep: /home/appbox/.config/Lidarr/config.xml: No such file or directory
grep: /home/appbox/.config/Lidarr/config.xml: No such file or directory
grep: /home/appbox/.config/Lidarr/config.xml: No such file or directory
grep: /home/appbox/.config/Lidarr/config.xml: No such file or directory
grep: /home/appbox/.config/Lidarr/config.xml: No such file or directory

**Comment by coder8338** [comment]
Are you using the latest version?

I cant reproduce your error.

**Comment by Pagnor** [comment]
Yeah Im using 20.04 script just ran it again and it worked fine perhaps lidarr were playing with there files
