### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Pagnor** [coder8338/appbox_installer#26]
Could you look at adding Overweerr to the list https://overseer.dev

**Comment by coder8338** [comment]
FIxed by 33df2b11082becf6c9d75a3e0ad4e51a965ab79e, not tested so ymmv, let me know how it goes.

**Comment by Pagnor** [comment]
I tried it and it seems to of installed but cant get to it with either localhost:5055 or my appboxname/overseer

**Comment by kelvinguy85** [comment]
would really like a working version of this looks much better than ombi

**Comment by coder8338** [comment]
This is fixed by bb520b7aa4c85269e5e52ca5622656bf3c44456e
