### ISSUE TITLE
Error Installing lidarr

### ISSUE THREAD

**Issue by Pagnor** [coder8338/appbox_installer#27]
When installing lidarr i get
tar (child): Lidarr.develop.*.linux.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
chown: cannot access '/home/appbox/appbox_installer/Lidarr': No such file or directory
grep: /home/appbox/.config/Lidarr/config.xml: No such file or directory
Cannot open assembly '/home/appbox/appbox_installer/Lidarr/Lidarr.exe': No such file or directory.
grep: /home/appbox/.config/Lidarr/config.xml: No such file or directory
grep: /home/appbox/.config/Lidarr/config.xml: No such file or directory
grep: /home/appbox/.config/Lidarr/config.xml: No such file or directory

The grep: /home part just keeps going and going

**Comment by coder8338** [comment]
What is the output of:

```
curl -I https://api.github.com/users/octocat/orgs
```

I think you're hitting the github API limit, I've had the same problem before. Sometimes you just have to get the timestamp from above convert it to your timezone using https://www.unixtimestamp.com/index.php and then do the install again a few seconds after the rate limit has reset.

**Comment by coder8338** [comment]
@Pagnor can you try again? Closing this now as it's not a problem with the script.

**Comment by coder8338** [comment]
Seems like there was an error in the code, this should work now.
