### ISSUE TITLE
radarr not working 

### ISSUE THREAD

**Issue by casean5** [coder8338/appbox_installer#28]
radarr will not in stall right it look like its the same thing with the person having problomes with lidarr

**Comment by casean5** [comment]
appbox@ubuntumoives ~ $ curl -I https://api.github.com/users/octocat/orgs
HTTP/2 403 
date: Tue, 01 Jun 2021 13:36:55 GMT
server: Varnish
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
content-security-policy: default-src 'none'; style-src 'unsafe-inline'
access-control-allow-origin: *
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset
content-type: application/json; charset=utf-8
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
x-github-media-type: github.v3; format=json
x-ratelimit-limit: 60
x-ratelimit-remaining: 0
x-ratelimit-reset: 1622557437
x-ratelimit-resource: core
x-ratelimit-used: 60
content-length: 281
x-github-request-id: 8118:1E64:4AF2B42:4D3894B:60B637F7

**Comment by Rid** [comment]
Please get the timestamp from `x-ratelimit-reset` above convert it to your timezone using https://www.unixtimestamp.com/index.php and then do the install again a few seconds after the rate limit has reset.

**Comment by coder8338** [comment]
Please get the timestamp from `x-ratelimit-reset` above convert it to your timezone using https://www.unixtimestamp.com/index.php and then do the install again a few seconds after the rate limit has reset.

**Comment by casean5** [comment]
> Please get the timestamp from `x-ratelimit-reset` above convert it to your timezone using https://www.unixtimestamp.com/index.php and then do the install again a few seconds after the rate limit has reset.

i do and i check and i am all ready rate limit and i do even do it anything

**Comment by coder8338** [comment]
@casean5 can you try again? Closing this now as it's not a problem with the script.
