### ISSUE TITLE
Overseerr installation 502 Bad Gateway

### ISSUE THREAD

**Issue by wayomosqueda** [coder8338/appbox_installer#29]
Hi, thank you so much for this script is really awesome!

I tried the installation twice and in both times, the result of the installation was a 502 Bad Gateway error. I have the Ombi, Radarr and Sonarr installation with your script and those work perfectly. Any idea if there's something missing?

Thank you again for your kind and hard work!

**Comment by coder8338** [comment]
Was there any errors from the script during the installation? Can you please paste the entire install log here?
