### ISSUE TITLE
Access from other server

### ISSUE THREAD

**Issue by wayomosqueda** [coder8338/appbox_installer#30]
Maybe this is a dumb question, sorry if it is...

Is there a way to access these installations from another server? For example, if I have an Overseerr instalation in another server, but I want to access my radarr and sonarr on the appbox server, it requests a hostname or ip and a port, but ubuntu.appbox_user.appboxes.co:7878 won't open Radarr.  And I can't use the /radarr Url Base because that's not a valid hostname or IP.

Thank you for your hard work, have a great day!

**Comment by coder8338** [comment]
For a remote server the port should be 443 you should use SSL and the base URL should be /radarr.

If the app you're using doesn't allow you to enter those options, then please open an issue with the app developer asking for them, they're pretty basic settings 🤣
