### ISSUE TITLE
Support for Requestrr

### ISSUE THREAD

**Issue by ghost** [coder8338/appbox_installer#31]
Hey, it would be very useful with added support for "requestrr": https://github.com/darkalfx/requestrr

It works nice in combination with Ombi/Sonarr/Radarr

**Comment by ghost** [comment]
You know what, I was being lazy, asking for stuff I could create myself.

I made a pull-request for this:
https://github.com/coder8338/appbox_installer/pull/32

**Comment by coder8338** [comment]
Thanks @VP-EN, I've closed this now by pulling #32.

Feel free to make more PRs like this!!
