### ISSUE TITLE
Issue installing Sabnzbdplus

### ISSUE THREAD

**Issue by Pagnor** [coder8338/appbox_installer#34]
Currently hitting an issue where people are trying to install Saband it wont load or icon shows for few seconds then goes Ive tried on a demo box and I seem to be seeing this error

aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Elementary/odin

This seems to be isolated to the latest update 20.04-5

**Comment by coder8338** [comment]
Fixed by 5680d14bde9ca53a0bdeaba8f38ff8ce33d8b03b
