### ISSUE TITLE
AutoScan Request 

### ISSUE THREAD

**Issue by jaylex32** [coder8338/appbox_installer#35]
Can you guys please add AutoScan on this amazing app?
Here is the project link:
https://github.com/Cloudbox/autoscan

Thanks

**Comment by rollecode** [comment]
Should be rather easy to implement. I could do it during following days. I have to ask, what is it for? I mean why the internal scanning mechanism provided by Plex isn't enough?

**Comment by coder8338** [comment]
Closing this as @jaylex32 hasn't replied and I'm not sure there's much demand for this.

**Comment by jaylex32** [comment]
> Should be rather easy to implement. I could do it during following days. I have to ask, what is it for? I mean why the internal scanning mechanism provided by Plex isn't enough?

no is not enough for someone that is using rclone storage drives linked to Plex. when you use a cloud storage with Plex the autoscan feature doesn't work.
