### ISSUE TITLE
INTERNAL PAGE ERROR: After Installing Bazarr

### ISSUE THREAD

**Issue by AnythingOldSkewl** [coder8338/appbox_installer#39]
LOG:

Enter the option and press [ENTER]: 12

Setting up bazarr..
s6-svc: fatal: unable to control /run/s6/services/bazarr: No such file or directory
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease                                          
Hit:3 http://ppa.launchpad.net/elementary-os/daily/ubuntu focal InRelease                               
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease                                        
Hit:5 http://ppa.launchpad.net/elementary-os/os-patches/ubuntu focal InRelease                          
Hit:6 http://download.mono-project.com/repo/ubuntu focal InRelease                                      
Hit:7 http://ppa.launchpad.net/jcfp/ppa/ubuntu focal InRelease                                          
Hit:8 http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu focal InRelease               
Hit:9 http://ppa.launchpad.net/stebbins/handbrake-releases/ubuntu focal InRelease                       
Hit:10 https://apt.sonarr.tv/ubuntu focal InRelease                                                     
Hit:11 http://security.ubuntu.com/ubuntu focal-security InRelease                                       
Hit:12 https://packages.microsoft.com/ubuntu/20.04/prod focal InRelease
Ign:13 https://mkvtoolnix.download/ubuntu focal InRelease
Hit:14 https://mkvtoolnix.download/ubuntu focal Release
Reading package lists... Done
Building dependency tree      
Reading state information... Done
222 packages can be upgraded. Run 'apt list --upgradable' to see them.
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://download.mono-project.com/repo/ubuntu focal InRelease' doesn't support architecture 'i386'
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't support architecture 'i386'
W: Skipping acquire of configured file 'deb-src/binary-i386/Packages' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'deb-src' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'deb-src/binary-amd64/Packages' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'deb-src' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'deb-src/dep11/Components-amd64.yml' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'deb-src' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'deb-src/dep11/icons-48x48.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'deb-src' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'deb-src/dep11/icons-64x64.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'deb-src' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'deb-src/dep11/icons-64x64@2.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'deb-src' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'deb-src/dep11/icons-128x128.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'deb-src' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'https://mkvtoolnix.download/ubuntu//binary-i386/Packages' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'https://mkvtoolnix.download/ubuntu/' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'https://mkvtoolnix.download/ubuntu//binary-amd64/Packages' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'https://mkvtoolnix.download/ubuntu/' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'https://mkvtoolnix.download/ubuntu//dep11/Components-amd64.yml' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'https://mkvtoolnix.download/ubuntu/' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'https://mkvtoolnix.download/ubuntu//dep11/icons-48x48.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'https://mkvtoolnix.download/ubuntu/' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'https://mkvtoolnix.download/ubuntu//dep11/icons-64x64.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'https://mkvtoolnix.download/ubuntu/' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'https://mkvtoolnix.download/ubuntu//dep11/icons-64x64@2.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'https://mkvtoolnix.download/ubuntu/' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'https://mkvtoolnix.download/ubuntu//dep11/icons-128x128.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'https://mkvtoolnix.download/ubuntu/' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'focal/binary-i386/Packages' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'focal' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'focal/binary-amd64/Packages' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'focal' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'focal/dep11/Components-amd64.yml' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'focal' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'focal/dep11/icons-48x48.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'focal' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'focal/dep11/icons-64x64.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'focal' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'focal/dep11/icons-64x64@2.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'focal' (component misspelt in sources.list?)
W: Skipping acquire of configured file 'focal/dep11/icons-128x128.tar' as repository 'https://mkvtoolnix.download/ubuntu focal InRelease' doesn't have the component 'focal' (component misspelt in sources.list?)
Reading package lists... Done
Building dependency tree      
Reading state information... Done
Note, selecting 'git' instead of 'git-core'
git is already the newest version (1:2.25.1-1ubuntu3.1).
python3-distutils is already the newest version (3.8.10-0ubuntu1~20.04).
python3-distutils set to manually installed.
The following packages were automatically installed and are no longer required:
  fprintd libfprint-2-2 libpam-fprintd
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python-pip-whl
The following packages will be upgraded:
  python-pip-whl python3-pip
2 upgraded, 0 newly installed, 0 to remove and 220 not upgraded.
Need to get 2036 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 python3-pip all 20.0.2-5ubuntu1.6 [231 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 python-pip-whl all 20.0.2-5ubuntu1.6 [1805 kB]
Fetched 2036 kB in 0s (17.4 MB/s)   
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 160882 files and directories currently installed.)
Preparing to unpack .../python3-pip_20.0.2-5ubuntu1.6_all.deb ...
Unpacking python3-pip (20.0.2-5ubuntu1.6) over (20.0.2-5ubuntu1.5) ...
Preparing to unpack .../python-pip-whl_20.0.2-5ubuntu1.6_all.deb ...
Unpacking python-pip-whl (20.0.2-5ubuntu1.6) over (20.0.2-5ubuntu1.5) ...
Setting up python-pip-whl (20.0.2-5ubuntu1.6) ...
Setting up python3-pip (20.0.2-5ubuntu1.6) ...
Processing triggers for man-db (2.9.1-1) ...
Cloning into 'bazarr'...
remote: Enumerating objects: 4816, done.
remote: Counting objects: 100% (4816/4816), done.
remote: Compressing objects: 100% (4043/4043), done.
remote: Total 4816 (delta 575), reused 3895 (delta 492), pack-reused 0
Receiving objects: 100% (4816/4816), 29.79 MiB | 12.62 MiB/s, done.
Resolving deltas: 100% (575/575), done.
Updating files: 100% (4369/4369), done.
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (45.2.0)
Collecting gevent>=21
  Downloading gevent-21.8.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.5 MB)
     |████████████████████████████████| 6.5 MB 25.6 MB/s
Collecting gevent-websocket>=0.10.1
  Downloading gevent_websocket-0.10.1-py3-none-any.whl (22 kB)
Collecting lxml>=4.3.0
  Downloading lxml-4.6.3-cp38-cp38-manylinux2014_x86_64.whl (6.8 MB)
     |████████████████████████████████| 6.8 MB 38.9 MB/s
Requirement already satisfied: numpy>=1.12.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 5)) (1.17.4)
Collecting webrtcvad-wheels>=2.0.10
  Downloading webrtcvad_wheels-2.0.10.post2-cp38-cp38-manylinux2010_x86_64.whl (85 kB)
     |████████████████████████████████| 85 kB 1.5 MB/s
Collecting greenlet<2.0,>=1.1.0; platform_python_implementation == "CPython"
  Downloading greenlet-1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (150 kB)
     |████████████████████████████████| 150 kB 52.2 MB/s
Collecting zope.event
  Downloading zope.event-4.5.0-py2.py3-none-any.whl (6.8 kB)
Requirement already satisfied: zope.interface in /usr/lib/python3/dist-packages (from gevent>=21->-r requirements.txt (line 2)) (4.7.1)
ERROR: flexget 3.1.131 has requirement greenlet==1.0.0, but you'll have greenlet 1.1.1 which is incompatible.
Installing collected packages: greenlet, zope.event, gevent, gevent-websocket, lxml, webrtcvad-wheels
  Attempting uninstall: greenlet
    Found existing installation: greenlet 1.0.0
    Uninstalling greenlet-1.0.0:
      Successfully uninstalled greenlet-1.0.0
Successfully installed gevent-21.8.0 gevent-websocket-0.10.1 greenlet-1.1.1 lxml-4.6.3 webrtcvad-wheels-2.0.10.post2 zope.event-4.5.0
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
Bazarr starting...
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory
grep: /home/appbox/appbox_installer/bazarr/data/config/config.ini: No such file or directory

Session terminated, killing shell...s6-svc: fatal: unable to control /run/s6/services/bazarr: supervisor not listening

**Comment by rollecode** [comment]
Just noticed the same thing. How to resolve?

**Comment by AnythingOldSkewl** [comment]
> Just noticed the same thing. How to resolve?

I didn't find a solution. This coder response when he wants too. It's obvious he has no desire to support his own code. I guess the only solution is to install it manually. But, I lost interest after a while.

**Comment by ronilaukkarinen** [comment]
Got it to work. Baseurl is wrong in installation, it should be `/bazarr`. Edit: `sudo nano /APPBOX_DATA/apps/ubuntu.peikko.appboxes.co/appbox_installer/bazarr/data/config/config.ini`, then restart bazarr and nginx.

**Comment by rollecode** [comment]
Got it to work. Baseurl is wrong in installation, it should be `/bazarr`. Edit: `sudo nano /APPBOX_DATA/apps/ubuntu.YOURSERVERNAME.appboxes.co/appbox_installer/bazarr/data/config/config.ini`, then restart bazarr and nginx.

**Comment by gwenvador** [comment]
Is bazarr working for you? The baseurl is correct for me but I cannot modify any settings. It keeps loading when clicking save.

**Comment by rollecode** [comment]
Yeah, for me the config.ini first lines are:

```
[general]
ip = 0.0.0.0
port = 6767
base_url = /bazarr
```

Had to restart couple of times with `sudo s6-svc -r /run/s6/services/bazarr/`. If `sudo tail -f /var/log/appbox/bazarr/current` shows it running correctly, it should work.

**Comment by gwenvador** [comment]
Sorry what I wanted to say is that starting bazarr is fine but I cannot modify any settings in the GUI. It keeps loading when saving. I tried modifying permission for the config.ini but it is still the same issue. If everything is working fine for you it is me on my side. Trying to get a feedback.

**Comment by rollecode** [comment]
Oh, OK. I don't have those issues.

**Comment by coder8338** [comment]
> > Just noticed the same thing. How to resolve?
> 
> I didn't find a solution. This coder response when he wants too. It's obvious he has no desire to support his own code. I guess the only solution is to install it manually. But, I lost interest after a while.

Dont be a dick, I do this out of kindness! I'm checking this for any issue atm

**Comment by coder8338** [comment]
> Sorry what I wanted to say is that starting bazarr is fine but I cannot modify any settings in the GUI. It keeps loading when saving. I tried modifying permission for the config.ini but it is still the same issue. If everything is working fine for you it is me on my side. Trying to get a feedback.

I cannot reproduce this, please open a new issue.

**Comment by AnythingOldSkewl** [comment]
You waited almost two months to respond to this, and you call me a dick? You've got some nerve, you unstable f**k! I can see you got real customer service skills. Time for you meds dude.

**Comment by rollecode** [comment]
> You waited almost two months to respond to this, and you call me a dick? You've got some nerve, you unstable f**k! I can see you got real customer service skills. Time for you meds dude.

Wow... Just wow. Never seen such disrespect towards a maintainer in my life. Your comment speaks for itself.

**Comment by AnythingOldSkewl** [comment]
> 
> 
> > You waited almost two months to respond to this, and you call me a dick? You've got some nerve, you unstable f**k! I can see you got real customer service skills. Time for you meds dude.
> 
> Wow... Just wow. Never seen such disrespect towards a maintainer in my life. Your comment speaks for itself.

Why did you willfully ignored the fact he called me a dick? Yet, you make me the bad guy..  People only see what the want to see on the internet.

**Comment by rollecode** [comment]
> > > You waited almost two months to respond to this, and you call me a dick? You've got some nerve, you unstable f**k! I can see you got real customer service skills. Time for you meds dude.
> > 
> > 
> > Wow... Just wow. Never seen such disrespect towards a maintainer in my life. Your comment speaks for itself.
> 
> Why did you willfully ignored the fact he called me a dick? Yet, you make me the bad guy.. People only see what the want to see on the internet.

Exactly. He didn't call you a dick. He literally said don't be a dick. And now you are acting like one. Again, your last sentence proves the point. Have a nice day! 😘

**Comment by AnythingOldSkewl** [comment]
> 
> 
> > > > You waited almost two months to respond to this, and you call me a dick? You've got some nerve, you unstable f**k! I can see you got real customer service skills. Time for you meds dude.
> > > 
> > > 
> > > Wow... Just wow. Never seen such disrespect towards a maintainer in my life. Your comment speaks for itself.
> > 
> > 
> > Why did you willfully ignored the fact he called me a dick? Yet, you make me the bad guy.. People only see what the want to see on the internet.
> 
> Exactly. He didn't call you a dick. He literally said don't be a dick. And now you are acting like one. Again, your last sentence proves the point. Have a nice day! 😘

This is why people like that continue to be disrespectful, because people like you encourage them. Both of you are idiots.

**Comment by coder8338** [comment]
> You waited almost two months to respond to this, and you call me a dick? You've got some nerve, you unstable f**k! I can see you got real customer service skills. Time for you meds dude.

Holy shit man, you are not my customer, I'm not trying to get you to use this. I made it because I used it myself and thought it would be cool for other people to contribute.

You're a leech, you contribute no code and treat maintainers like they're your slaves, it's people like you that really peeve OSS maintainers.

Submit some code and fix it yourself dude!

**Comment by AnythingOldSkewl** [comment]
> 
> 
> > You waited almost two months to respond to this, and you call me a dick? You've got some nerve, you unstable f**k! I can see you got real customer service skills. Time for you meds dude.
> 
> Holy shit man, you are not my customer, I'm not trying to get you to use this. I made it because I used it myself and thought it would be cool for other people to contribute.
> 
> You're a leech, you contribute no code and treat maintainers like they're your slaves, it's people like you that really peeve OSS maintainers.
> 
> Submit some code and fix it yourself dude!

That's no excuse to call me a dick. If the roles were reversed, you would have taken every opportunity to vilify me. Second, I don't care if you're volunteering your services. Common sense, you don't leave people hangin' for almost two months, and try to use the excuse "I'm just doin' it as a favor," or whatever. It's not like you get thousands of posts a week. After a week, out of courtesy you should have at least said you were busy or something. When people use your script, it's inevitable we will need help. So, if people are eager to use something, that's tied in to the seedbox we're paying for, of course we're gonna get a little upset. If you don't have people skills, or you know you're not a people person, or don't know how to handle people in certain situations, perhaps you shouldn't offer your skills to the general public.

**Comment by gwenvador** [comment]
> > > You waited almost two months to respond to this, and you call me a dick? You've got some nerve, you unstable f**k! I can see you got real customer service skills. Time for you meds dude.
> > 
> > 
> > Holy shit man, you are not my customer, I'm not trying to get you to use this. I made it because I used it myself and thought it would be cool for other people to contribute.
> > You're a leech, you contribute no code and treat maintainers like they're your slaves, it's people like you that really peeve OSS maintainers.
> > Submit some code and fix it yourself dude!
> 
> That's no excuse to call me a dick. If the roles were reversed, you would have taken every opportunity to vilify me. Second, I don't care if you're volunteering your services. Common sense, you don't leave people hangin' for almost two months, and try to use the excuse "I'm just doin' it as a favor," or whatever. It's not like you get thousands of posts a week. After a week, out of courtesy you should have at least said you were busy or something. When people use your script, it's inevitable we will need help. So, if people are eager to use something, that's tied in to the seedbox we're paying for, of course we're gonna get a little upset. If you don't have people skills, or you know you're not a people person, or don't know how to handle people in certain situations, perhaps you shouldn't offer your skills to the general public.

Man why don't you shut up and go somewhere else. We don't need you here and your negativity. You obviously don't know what it is to be volunteer open source developer. It is because of people like you that many developer are getting more and more frustrated. You don't know who is coder8338 so GTFO.

**Comment by AnythingOldSkewl** [comment]
> 
> 
> > > > You waited almost two months to respond to this, and you call me a dick? You've got some nerve, you unstable f**k! I can see you got real customer service skills. Time for you meds dude.
> > > 
> > > 
> > > Holy shit man, you are not my customer, I'm not trying to get you to use this. I made it because I used it myself and thought it would be cool for other people to contribute.
> > > You're a leech, you contribute no code and treat maintainers like they're your slaves, it's people like you that really peeve OSS maintainers.
> > > Submit some code and fix it yourself dude!
> > 
> > 
> > That's no excuse to call me a dick. If the roles were reversed, you would have taken every opportunity to vilify me. Second, I don't care if you're volunteering your services. Common sense, you don't leave people hangin' for almost two months, and try to use the excuse "I'm just doin' it as a favor," or whatever. It's not like you get thousands of posts a week. After a week, out of courtesy you should have at least said you were busy or something. When people use your script, it's inevitable we will need help. So, if people are eager to use something, that's tied in to the seedbox we're paying for, of course we're gonna get a little upset. If you don't have people skills, or you know you're not a people person, or don't know how to handle people in certain situations, perhaps you shouldn't offer your skills to the general public.
> 
> Man why don't you shut up and go somewhere else. We don't need you here and your negativity. You obviously don't know what it is to be volunteer open source developer. It is because of people like you that many developer are getting more and more frustrated. You don't know who is coder8338 so GTFO.

REAL volunteers are helpful. No REAL volunteer is gonna call someone they don't know a dick! So, YOU shut the fuck up and mind your business!!

**Comment by gwenvador** [comment]
I care because developer are valuable resources and deserve appreciation for the work done.  Stop bitching and appreciate what you have. People have life outside internet. I will stop feeding the troll now.

**Comment by AnythingOldSkewl** [comment]
> 
> 
> I care because developer are valuable resources and deserve appreciation for the work done. Stop bitching and appreciate what you have. People have life outside internet. I will stop feeding the troll now.

You must be a teenager/generation X. You guys have no clue as to what respect means.  How about I start calling you a dick? Then again, in this day and age, you'd probably like it.
