### ISSUE TITLE
Uninstall option

### ISSUE THREAD

**Issue by LOCKSPORT1** [coder8338/appbox_installer#40]
Any way to uninstall apps installed with the installer?

**Comment by rollecode** [comment]
I'd also like to know this. Is there any tutorial on how to clean up things? Related to [this](https://github.com/coder8338/appbox_installer/issues/55) I'd like to try and uninstall an app one by one and figure out which is defunct...

**Comment by coder8338** [comment]
There's no way, happy to accept a PR though, should be pretty simple to do manually, just remove the folder from `/etc/services.d/<app name>` and `/home/appbox/appbox_installer/<app name>`  then restart ubuntu.

**Comment by coder8338** [comment]
> I'd also like to know this. Is there any tutorial on how to clean up things? Related to [this](https://github.com/coder8338/appbox_installer/issues/55) I'd like to try and uninstall an app one by one and figure out which is defunct...

Why didn't you just check the defunct pid? `cat /proc/<PID>/cmdline` should tell you which app is causing it.

**Comment by rollecode** [comment]
> Why didn't you just check the defunct pid? `cat /proc/<PID>/cmdline` should tell you which app is causing it.

Because I couldn't access the box any longer, after getting ps command go through was completely cut off 😅

**Comment by AliceDTRH** [comment]
> There's no way, happy to accept a PR though, should be pretty simple to do manually, just remove the folder from `/etc/services.d/<app name>` and `/home/appbox/appbox_installer/<app name>` then restart ubuntu.

Most application installations include some steps that are done outside of those folders and we don't know if the application has made more changes to the system afterwards. I don't believe there's a safe way to *fully* uninstall apps and uninstalling it partly could cause issues as well.

I can send you a PR that takes the steps you indicated if you think it will be enough though.

**Comment by coder8338** [comment]
@AliceDTRH I think best effort is enough, reinstalling would overwrite all of those files anyway.

Of course to fully clean up we'd need to also uninstall packages using apt, that would require a function for most apps, you can add that if you wish (it's probably a lot of work), but stopping the service is a good first step anyway.

**Comment by coder8338** [comment]
I'm not maintaining this installer anymore. Switching to a new way of installing apps: https://github.com/coder8338/appbox_swizzin_installer

This includes an uninstall option.
