### ISSUE TITLE
Komga issue with encoding with s6-supervise

### ISSUE THREAD

**Issue by gwenvador** [coder8338/appbox_installer#41]
Komga is not working properly under the s6-supervise program. The problem is when adding comics with special character:
`java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters:`
It seems this is has to do with encoding as launching komga from normal user (appbox or root) is working fine. 
I am not familiar with s6-supervice so not sure where to look for this issue.

**Comment by gwenvador** [comment]
The problem is in the locale when s6 supervisor is launched. On my box it is POSIX instead of UTF-8 (as my appbox user). So the script should be run with s6-envdir (with a directory of ENV files) but I find it not very elegant. Not sure if you have a better solution for this issue.

**Comment by coder8338** [comment]
@gwenvador can you try the latest version, or you could try:

```
FILENAME=$(ls -la /home/appbox/appbox_installer/komga | grep jar | awk '{print $9}')
cat << EOF > /etc/services.d/komga/run
#!/usr/bin/with-contenv bash

s6-setuidgid appbox

/usr/bin/java -jar /home/appbox/appbox_installer/komga/${FILENAME} --server.servlet.context-path="/komga" --server.port=8443 2>&1
EOF
```

Then restart Ubuntu?
