### ISSUE TITLE
Overseerr

### ISSUE THREAD

**Issue by Pagnor** [coder8338/appbox_installer#45]
Seems to be an issue when installing overseerr new version 1.26 doesn't seem to install correctly after install the link gives an error 502

**Comment by rollecode** [comment]
What does your log says? `sudo cat /var/log/appbox/overseerr/current`

I haven't encountered any issues with overseerr or after install/reinstall but FYI the JS app rewrites urls so that if you try to access them by linking, it will not work, you just need to go yourdomain/overseerr and it works.

The latest version is [1.26.1 (2021-09-20)](https://github.com/sct/overseerr/releases/tag/v1.26.1) and is released 13 days ago, maybe try and reinstall?

**Comment by rollecode** [comment]
Just upgraded from 1.25 to 1.26.1 and seems to work fine. Installing it took a while but no problems whatsoever.

![image](https://user-images.githubusercontent.com/1534150/135724698-41194a3a-d881-4279-9257-679047b3ac3a.png)

**Comment by Pagnor** [comment]
I ended up putting it on a dedicated box

**Comment by rollecode** [comment]
The app runs fine, just noticed there's only two minor image path issues that will be fixed in [this PR](https://github.com/coder8338/appbox_installer/pull/54#issuecomment-932780275) I just sent. After merging this issue can be closed (ping @coder8338).

**Comment by Pagnor** [comment]
This is still an issue as a client has now posted about the same issue I reported

**Comment by rollecode** [comment]
> What does your log says? sudo cat /var/log/appbox/overseerr/current

Needing more information to help I'm afraid.

I personally switched boxes so I can't say anymore in appbox environment. However, I have installed Overseerr with exactly the same settings than in this repo and having no issues whatsoever.

**Comment by coder8338** [comment]
@Pagnor do you have the log from /var/log/appbox/overseerr/current ? Cant really do much without it

**Comment by coder8338** [comment]
@Pagnor did you try deleting the `/home/appbox/appbox_installer/overseerr/` folder before upgrading?

**Comment by wusa78** [comment]
Hi , i have this same issu , i have use the install script and want install overseerr but , i get a error 405 error wenn i try to connect the local web interface
