### ISSUE TITLE
Need .NET Core Version of Radarr

### ISSUE THREAD

**Issue by AnythingOldSkewl** [coder8338/appbox_installer#5]
Hi @coder8338 !

The new script doesn't appear to have the .NET Core version (Radarr suggested after installation). I've contacted my seedbox, and I know they're gonna redirect me to you. Is there a way to have me Radarr properly installed with the correct version?

https://thumbs2.imgbox.com/ca/5d/K6o2c9lV_t.png

Thanks.

**Comment by coder8338** [comment]
@AnythingOldSkewl the script was updated to the latest version a few days ago.
