### ISSUE TITLE
Could you look at adding Overseerr? (feature request)

### ISSUE THREAD

**Issue by mastervash** [coder8338/appbox_installer#56]
If it would be possible, I'd love for Overseerr to be considered to be added to the script. I realize that most of the installs call for Docker. However snap does have a non-dockerized version (to the best of my knowledge anyway). Swizzin also has a barebones build, although it has not been merged yet. This would truly make appbox my one and only seedbox solution. 
[https://docs.overseerr.dev/](https://docs.overseerr.dev/
)

Thank you again.

**Comment by coder8338** [comment]
This is already added on the Ubuntu 20.04 version, I'm no longer supporting 18.04 but you are welcome to submit a PR for it if you're still using it.
