### ISSUE TITLE
Ombi v4

### ISSUE THREAD

**Issue by Hhhonlyfan** [coder8338/appbox_installer#57]
Ombi v4 won't load up for myself.

Get blank screen or nginx writing. It's only on ombi v4 that it happening. 

Issue is like this one https://github.com/Ombi-app/Ombi/issues/3931

Wondering if there's any fix?

**Comment by AliceDTRH** [comment]
https://github.com/Ombi-app/Ombi/issues/3483#issuecomment-787753428
^-- Note to self/dev

**Comment by coder8338** [comment]
@AliceDTRH is this fixed? Seems from the dev that it appears to be?

**Comment by AliceDTRH** [comment]
The recent versions of Ombi include a fix for the issue they mentioned in their ticket, but I don't know if @Hhhonlyfan has any remaining issues?

**Comment by Hhhonlyfan** [comment]
> The recent versions of Ombi include a fix for the issue they mentioned in their ticket, but I don't know if @Hhhonlyfan has any remaining issues?

It still happens on th my domain.com/v4ombi link 

But the standard one is working fine.
