### ISSUE TITLE
Can you look at adding Gaps

### ISSUE THREAD

**Issue by Pagnor** [coder8338/appbox_installer#58]
Can you look and see if you can add gaps to the list it runs in docker

https://reposhub.com/java/miscellaneous/JasonHHouse-Gaps.html

**Comment by coder8338** [comment]
It would be possible to just use the jar I think, does anyone fancy having a go at this?

**Comment by coder8338** [comment]
I'm not maintaining this installer anymore. Switching to a new way of installing apps: https://github.com/coder8338/appbox_swizzin_installer
