### ISSUE TITLE
Please Add New Lidarr

### ISSUE THREAD

**Issue by AnythingOldSkewl** [coder8338/appbox_installer#6]
Please add the new Lidarr to the script.. Thanks..

**Comment by coder8338** [comment]
The script automatically downloads the latest version, unless they updated a dependency? Am I missing something? If so please link me to docs.

**Comment by AnythingOldSkewl** [comment]
All I know is that I'm on version **0.7.1.1381**, which is a year old, and verison 0.7.2.1878 is now available.  There is a message at the top of Lidarr that says "An update is available. Please update your Docker image and re-create the container." I don't know what any of that means.

**Comment by AnythingOldSkewl** [comment]
All I know is that I'm on version 0.7.1.1381, which is a year old, and version 0.7.2.1878 is now available. There is a message at the top of Lidarr that says "Please update your Docker image and re-create the container." I don't know what any of that means, and there are no source links given.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
