### ISSUE TITLE
debian version please

### ISSUE THREAD

**Issue by pazport** [coder8338/appbox_installer#63]
any chance of a installer for bedian please mate 👍

**Comment by coder8338** [comment]
I'm not maintaining this installer anymore. Switching to a new way of installing apps: https://github.com/coder8338/appbox_swizzin_installer

It should be easy to fork it for debian, I will try shortly.

**Comment by coder8338** [comment]
Here's the debian version: https://github.com/coder8338/appbox_swizzin_installer/tree/Debian_11
