### ISSUE TITLE
issue with overseerr

### ISSUE THREAD

**Issue by Pagnor** [coder8338/appbox_installer#64]
Getting this issue with overseerr v1.29 install 

An unexpected error occurred: "ENOTDIR: not a directory, lstat '/home/appbox/appbox_installer/overseerr/node_modules/react-ace/dist/react-ace.js/main.js'"

**Comment by coder8338** [comment]
I'm not maintaining this installer anymore. Switching to a new way of installing apps: https://github.com/coder8338/appbox_swizzin_installer
