### ISSUE TITLE
Need .NET Core Version of Radarr 

### ISSUE THREAD

**Issue by AnythingOldSkewl** [coder8338/appbox_installer#7]
The only links were given was this: [Link](https://wiki.servarr.com/Radarr_System#update-to-net-core-version)  I replaced the files as instructed, but Radarr still gives me the "need .NET Core version of Radarr" message. It also talks about modifying "start up files/configuration." I don't know those files are. I already opened up a ticket with my seedbox and they directed me to back to you.

**Comment by coder8338** [comment]
Again I would suggest deleting the radarr folder from /opt and re-run the script.

**Comment by coder8338** [comment]
@AnythingOldSkewl so can this issue be close?

**Comment by AnythingOldSkewl** [comment]
Yes.
