### ISSUE TITLE
Please Add New Lidarr

### ISSUE THREAD

**Issue by AnythingOldSkewl** [coder8338/appbox_installer#8]
All I know is that I'm on version **0.7.1.1381**, which is a year old, and version **0.7.2.1878** is now available. There is a message at the top of Lidarr that says "Please update your Docker image and re-create the container." I don't know what any of that means, and there are no source links given.

**Comment by coder8338** [comment]
You can try re-running the script, updating is out of the scope of this script as there's many edge-cases for each app. I think it should be fine though if you just delete the lidar folder from /opt and re-run the script.

**Comment by AnythingOldSkewl** [comment]
Oh sh*t! That seemed to work. So, Linux doesn't override files? You have to actually delete? I'm gonna try the same thing with Radarr now.

**Comment by coder8338** [comment]
@AnythingOldSkewl It will overwrite the files, but we want to also clear out the old extra ones, so it's better to delete first.
