### ISSUE TITLE
Look into adding PHP to the script for other dependencies

### ISSUE THREAD

**Issue by AliceDTRH** [coder8338/appbox_installer#9]

**Comment by AliceDTRH** [comment]
Work in progress

**Comment by AliceDTRH** [comment]
@coder8338 Is there any way I can contact you in a chat or something? I have an idea for the script but it would be more comfortable to discuss it in chat than in an issue.

**Comment by coder8338** [comment]
@AliceDTRH Sorry I'm busy at the moment, I'm not in the chat. I might be able to take a look at the rest of the issues next week.

**Comment by coder8338** [comment]
Closed by https://github.com/coder8338/appbox_installer/issues/10
